### PR TITLE
Dattatray patil patch 1 - Updated instruction as per latest power automate

### PR DESCRIPTION
**Pull request by ghost**
[Lab 0. Set up the new designer and the Community License.docx](https://github.com/Power-Automate-in-a-day/Training-by-the-community/files/5927921/Lab.0.Set.up.the.new.designer.and.the.Community.License.docx)
[Lab 1. Building a time tracking flow.docx](https://github.com/Power-Automate-in-a-day/Training-by-the-community/files/5927922/Lab.1.Building.a.time.tracking.flow.docx)

Due to recent changes in Power Automate, some screenshots and instructions not matching, hence updated and done nice formatting to the document. If you like it I will submit all other labs. Thank you!

Please note that I have only submitted Lab 0 and Lab 1 docx file. Thank you !

### CODE REVIEW

**Comment by sergeluca** [comment]
cool! that looks great. I will check that out this week-end. On Behalf of the Power Automate community, thank you ! Also you can add your name in an  "updated by" section  of the document 👍 -) I will get back to you

**Comment by ghost** [comment]
Thank you for reviewing. I will update in next week.

**Comment by sergeluca** [comment]
You can keep working on the labs. They are great, I will upload the first ones today - with your name!

**Comment by ghost** [comment]
Thank you for your kind words, I have now uploaded all the files. Kindly close my pull request, 
Also please review the additional document and do let me know if there is any specific section if I need to re-check.

Thank you!

**Pull request closed without merging**
